name: dwl_iptv
description: "IPTV downloader"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1                     # téléchargement avec suivi de progression
  path_provider: ^2.1.5             # accéder aux répertoires locaux
  flutter_secure_storage: ^9.2.4    # stockage sécurisé
  connectivity_plus: ^6.1.3         # vérifier la connectivité réseau
  device_info_plus: ^11.3.3         # informations sur l'appareil
  permission_handler: ^11.3.1       # gestion des permissions
  media_store_plus: ^0.1.3          # enregistrer des fichiers multimédias dans la galerie
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24

flutter_native_splash:
  android: true
  ios: false
  web: false
  # Logo centré
  image: assets/splash/splash.png

  # ✅ Dégradé via image pour Android ≤ 11
  background_image: assets/splash/bg_cyberpunk.png
  color: "#E7E8E9"

  # 📱 Spécifique Android 12+ (pas d'image de fond possible)
  android_12:
    image: assets/splash/splash.png
    color: "#E7E8E9"
    color_dark: "#E7E8E9"
    image_dark: assets/splash/splash.png