name: aetherStream
description: AetherStream (multi-comptes, playlist M3U, lecture, téléchargement)
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dio: ^5.5.0                       # téléchargement avec suivi de progression
  path_provider: ^2.1.5             # accéder aux répertoires locaux
  flutter_secure_storage: ^9.2.4    # stockage sécurisé
  connectivity_plus: ^7.0.0         # vérifier la connectivité réseau
  device_info_plus: ^12.2.0         # informations sur l'appareil
  permission_handler: ^12.0.1       # gestion des permissions
  media_store_plus: ^0.1.3          # enregistrer des fichiers multimédias dans la galerie
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  open_file_plus: ^3.4.1+1
  video_player: ^2.10.1
  chewie: ^1.13.0
  scrollable_positioned_list: ^0.3.8
  cached_video_player_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/AetherStreamIcon.png"
  min_sdk_android: 24

flutter_native_splash:
  android: true
  ios: false
  web: false

  # Logo centré
  image: assets/splash/AetherStreamIconSplash.png

  # ----------------------------------------------------
  # ✅ CORRECTION APPLIQUÉE ICI
  # ----------------------------------------------------

  # Pour Android 11 et inférieur (le background_image sera prioritaire)
  color: "#F5F5F5"          # Fond blanc pour le mode clair
  color_dark: "#000000"     # Fond noir pour le mode sombre

  # Image de fond pour un effet stylisé sur les anciennes versions
  background_image: assets/splash/AetherStreamSplash.png
  background_image_dark: assets/splash/AetherStreamDarkSplash.png

  # Spécifique pour Android 12+ (qui ne supporte pas background_image)
  # On utilise des couleurs unies qui correspondent au thème de l'app.
  android_12:
    image: assets/splash/AetherStreamSplash.png
    image_dark: assets/splash/AetherStreamDarkSplash.png
    color: "#F5F5F5"          # Fond blanc pour le mode clair
    color_dark: "#000000"     # Fond noir pour le mode sombre
